using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using IronPython.Hosting;
using Microsoft.Scripting;
using Microsoft.Scripting.Hosting;
using System.Diagnostics;
using System.IO;

namespace PythonInterop
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Console.WriteLine("Starting app...");

                ProcessStartInfo start = new ProcessStartInfo();
                start.FileName = @"C:\Users\{user}\AppData\Local\Programs\Python\Python35\python.exe";
                start.Arguments = string.Format("\"{0}\"", @"{repo path}\test.py");
                start.UseShellExecute = false;// Do not use OS shell
                start.CreateNoWindow = true; // We don't need a new window
                start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
                start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)

                using (Process process = Process.Start(start))
                {
                   using (StreamReader reader = process.StandardOutput)
                   {
                       string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                       string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                       Console.WriteLine(result);
                   }
                }

                Console.WriteLine("Finished, press any key to exit........");
                Console.ReadKey();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                Console.WriteLine("There was an error, press any key to exit........");
            }
        }
    }
}
